default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASS'] %>
  host: <%= ENV['DBHOST'] %>
  port: 5432

development:
  <<: *default
  database: <%= ENV['PGUSER'] %>

test:
  <<: *default
  database: <%= ENV['PGUSER'] %>_test

production:
  <<: *default
  database: <%= ENV['PGUSER'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASS'] %>
